Defensics CoAP: fixes for cases with long data packets
JuulLabs-OSS/BTPTesterCore pull request #36
Opened 2021-01-26 11:10 UTC by KKopyscinski

2021-01-26 11:10 UTC, KKopyscinski commented
@michal-narajowski Could you review this?

2021-01-26 11:48 UTC, michal-narajowski requested changes

2021-01-26 11:48 UTC, michal-narajowski commented on defensics/tcp_data_handler.py
> +                        if type(ex) == dbus.exceptions.DBusException:
You can handle exceptions separately.

2021-01-26 11:48 UTC, michal-narajowski commented on defensics/tcp_data_handler.py
> +                if self.proxy.is_ready():
Exit early to prevent huge indented chunks of code.

2021-01-26 11:48 UTC, michal-narajowski commented on defensics/tcp_data_handler.py
> +        skip = False
Overall this whole procedure is way too complicated. Refactor it into smaller methods with descriptive names. You can create a simple state machine to clearly define states. Proper error handling, less nested chunks of code.

2021-01-26 13:37 UTC, KKopyscinski commented
@michal-narajowski Done, I think readability is much better now

2021-02-03 13:42 UTC, michal-narajowski requested changes
I would simplify it a bit more. Having the CoaP Proxy and TCP server decoupled from the automation handler is nice but I think it may be a good idea to connect them in some way. 
How I see it:
- Each test case is separate
- In the before step, we initialize the TCP server and CoAP Proxy
- TCP server is rather stable so it should be fine but if there is an error -> fail test and tear down the entire setup
- If CoAP fails - handle exceptions properly. If an exception is unexpected -> fail the test and tear down the setup
- If it is expected (no response or disconnect) -> verify that there was no crash
- If there were no crash -> PASS -> tear down the setup
- If there was a crash -> FAIL -> capture whatever we can (optional) -> tear down the setup
- Next test case and do everything from the beginning
- In the teardown, you can flush all the additional data from the TCP server that the proxy cannot process.

I believe in this way we can avoid nested loops, exception handlers all over the place, and magic values.

2021-02-03 13:42 UTC, michal-narajowski commented on defensics/tcp_data_handler.py
>              if self.proxy.is_ready():
Exit early

2021-02-03 13:42 UTC, michal-narajowski commented on defensics/tcp_data_handler.py
> +                if self._send_or_pass(data):
Exit early, avoid nested code.

2021-02-03 13:53 UTC, KKopyscinski commented
@michal-narajowski Ok, I think I'll add another commit joining coap_automation_handler with rest of the code. As you said, running it independently is nice, but in to many places we need to interact with it. Also, ability access to tcp_server and proxy from this module simplifies a lot of things

2022-03-23 06:10 UTC, KKopyscinski commented
This is solved by https://github.com/JuulLabs-OSS/BTPTesterCore/pull/42, also, there is no point in testing packets longer than 512, as CoAP over BLE uses GATT Writes and more cannot be sent over radio

2022-03-23 06:10 UTC, closed without merging