Implement GATT_CL btp service
JuulLabs-OSS/BTPTesterCore pull request #48
Opened 2024-11-29 16:52 UTC by piotrnarajowski

- Implement GATT Client (0x06) BTP service. Relevant components are adjusted accordingly to ensure proper integration. 
- Helper functions for all necessary GATT procedures were added to reduce amount of code in GATT test case handlers and to choose between GATT/GATT_CL BTP commands depending on which one is supported by IUT
- Implement necessary tools for event handling
- Implement read supported services btp command. This is used when initializing GATT CL service

2025-01-22 10:03 UTC, piotrnarajowski commented
@KKopyscinski please review

2025-03-06 11:25 UTC, KKopyscinski approved these changes
This is quite a big change, but I know this is ported from auto-pts, so I assume it's okay. Would be nice if you could run the test set and leave comment with results to leave a mark that this was working. Also, if something doesn't pass, please check if this is a regression. Otherwise, LGTM.

2025-03-06 12:29 UTC, KKopyscinski commented on testcases/GattTestCase.py
> +        if stack.gatt_cl:
Maybe it is a good idea to abstract this logic as helper function, like so:
```suggestion
def gattc_disc_prim_svcs(addr1, addr2):
    if stack.gatt_cl:
            btp.gatt_cl_disc_prim_svcs(addr1, addr2)
            stack.gatt_cl.wait_for_prim_svcs()
            db = stack.gatt_cl.db
        else:
            btp.gattc_disc_prim_svcs(addr1, addr2)
            db = GattDB()
            btp.gattc_disc_prim_svcs_rsp(addr1, db)
    return db
```

and then, here do:
db = gattc_disc_prim_svcs(self.iut1, self.iut2.stack.gap.iut_addr_get())

applies to the rest of `if gatt_cl`, too

2025-03-06 12:44 UTC, piotrnarajowski commented on testcases/GattTestCase.py
> +        if stack.gatt_cl:
That's a great idea, will apply it

2025-03-06 12:53 UTC, KKopyscinski requested changes
I will mark this as changes requested so it won't be merged by accident before you're done

2025-03-07 12:02 UTC, piotrnarajowski commented on testcases/utils.py
> -
Fixed

2025-03-07 12:06 UTC, piotrnarajowski commented on testcases/GattTestCase.py
> +        if stack.gatt_cl:
@KKopyscinski Helper functions for all GATT procedures are now implemented and used in GATT test cases.
All tests finished with PASS verdict except for one which for some reason randomly fails at connection procedure. I'm looking into this issue right now but this is unrelated to test case handlers that this PR changes

![image](https://github.com/user-attachments/assets/bcce72b5-c306-45cf-89ee-3f0c64649121)

2025-03-07 13:18 UTC, KKopyscinski approved these changes
Nice, looks much more cleaner now!

2025-03-07 13:18 UTC, merged